// Mock data for football matches - used as fallback when API is unavailable

export const mockCompetitions = [
  {
    id: 2001,
    name: "UEFA Champions League",
    code: "CL",
    areaName: "Europe",
  },
  {
    id: 2002,
    name: "Premier League",
    code: "PL",
    areaName: "England",
  },
  {
    id: 2003,
    name: "La Liga",
    code: "LA",
    areaName: "Spain",
  },
  {
    id: 2004,
    name: "Serie A",
    code: "SA",
    areaName: "Italy",
  },
  {
    id: 2005,
    name: "Bundesliga",
    code: "BL",
    areaName: "Germany",
  },
  {
    id: 2006,
    name: "Ligue 1",
    code: "FL1",
    areaName: "France",
  },
];

export const mockTeams = [
  {
    id: 86,
    name: "Real Madrid CF",
    shortName: "Real Madrid",
    tla: "RMA",
    crest: "https://crests.football-data.org/86.png",
    areaName: "Spain",
  },
  {
    id: 87,
    name: "FC Barcelona",
    shortName: "Barcelona",
    tla: "BAR",
    crest: "https://crests.football-data.org/87.png",
    areaName: "Spain",
  },
  {
    id: 64,
    name: "Manchester United FC",
    shortName: "Manchester United",
    tla: "MUN",
    crest: "https://crests.football-data.org/64.png",
    areaName: "England",
  },
  {
    id: 65,
    name: "Manchester City FC",
    shortName: "Manchester City",
    tla: "MCI",
    crest: "https://crests.football-data.org/65.png",
    areaName: "England",
  },
  {
    id: 66,
    name: "Liverpool FC",
    shortName: "Liverpool",
    tla: "LIV",
    crest: "https://crests.football-data.org/66.png",
    areaName: "England",
  },
  {
    id: 67,
    name: "Arsenal FC",
    shortName: "Arsenal",
    tla: "ARS",
    crest: "https://crests.football-data.org/67.png",
    areaName: "England",
  },
  {
    id: 68,
    name: "Juventus",
    shortName: "Juventus",
    tla: "JUV",
    crest: "https://crests.football-data.org/68.png",
    areaName: "Italy",
  },
  {
    id: 69,
    name: "AC Milan",
    shortName: "AC Milan",
    tla: "MIL",
    crest: "https://crests.football-data.org/69.png",
    areaName: "Italy",
  },
  {
    id: 70,
    name: "Bayern Munich",
    shortName: "Bayern Munich",
    tla: "BAY",
    crest: "https://crests.football-data.org/70.png",
    areaName: "Germany",
  },
  {
    id: 71,
    name: "Paris Saint-Germain",
    shortName: "PSG",
    tla: "PSG",
    crest: "https://crests.football-data.org/71.png",
    areaName: "France",
  },
];

export const mockMatches = [
  {
    id: 1,
    competitionId: 2001,
    utcDate: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    status: "SCHEDULED",
    homeTeamId: 86,
    awayTeamId: 87,
    homeTeamScore: null,
    awayTeamScore: null,
    venue: "Santiago Bernabéu",
    matchday: 5,
    stage: "GROUP_STAGE",
  },
  {
    id: 2,
    competitionId: 2002,
    utcDate: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    status: "SCHEDULED",
    homeTeamId: 64,
    awayTeamId: 65,
    homeTeamScore: null,
    awayTeamScore: null,
    venue: "Old Trafford",
    matchday: 10,
  },
  {
    id: 3,
    competitionId: 2002,
    utcDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: "FINISHED",
    homeTeamId: 66,
    awayTeamId: 67,
    homeTeamScore: 2,
    awayTeamScore: 1,
    venue: "Anfield",
    matchday: 10,
    winner: "HOME",
  },
  {
    id: 4,
    competitionId: 2003,
    utcDate: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    status: "LIVE",
    minute: 45,
    homeTeamId: 86,
    awayTeamId: 87,
    homeTeamScore: 1,
    awayTeamScore: 0,
    venue: "Santiago Bernabéu",
    matchday: 8,
  },
  {
    id: 5,
    competitionId: 2004,
    utcDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
    status: "SCHEDULED",
    homeTeamId: 68,
    awayTeamId: 69,
    homeTeamScore: null,
    awayTeamScore: null,
    venue: "Allianz Stadium",
    matchday: 15,
  },
  {
    id: 6,
    competitionId: 2005,
    utcDate: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    status: "SCHEDULED",
    homeTeamId: 70,
    awayTeamId: 71,
    homeTeamScore: null,
    awayTeamScore: null,
    venue: "Allianz Arena",
    matchday: 12,
  },
];

export const mockMatchEvents = [
  {
    id: 1,
    matchId: 3,
    minute: 15,
    type: "GOAL",
    team: "HOME",
    player: "Mohamed Salah",
    playerId: 3192,
  },
  {
    id: 2,
    matchId: 3,
    minute: 28,
    type: "YELLOW_CARD",
    team: "AWAY",
    player: "Bukayo Saka",
    playerId: 3193,
  },
  {
    id: 3,
    matchId: 3,
    minute: 67,
    type: "GOAL",
    team: "HOME",
    player: "Luis Díaz",
    playerId: 3194,
  },
  {
    id: 4,
    matchId: 3,
    minute: 78,
    type: "SUBSTITUTION",
    team: "AWAY",
    player: "Bukayo Saka",
    playerIn: "Gabriel Martinelli",
  },
  {
    id: 5,
    matchId: 3,
    minute: 85,
    type: "GOAL",
    team: "AWAY",
    player: "Gabriel Jesus",
    playerId: 3195,
  },
];

export const mockStandings = [
  {
    position: 1,
    teamId: 86,
    teamName: "Real Madrid CF",
    playedGames: 10,
    won: 8,
    draw: 1,
    lost: 1,
    points: 25,
    goalsFor: 28,
    goalsAgainst: 8,
    goalDifference: 20,
  },
  {
    position: 2,
    teamId: 70,
    teamName: "Bayern Munich",
    playedGames: 10,
    won: 7,
    draw: 2,
    lost: 1,
    points: 23,
    goalsFor: 26,
    goalsAgainst: 10,
    goalDifference: 16,
  },
  {
    position: 3,
    teamId: 87,
    teamName: "FC Barcelona",
    playedGames: 10,
    won: 7,
    draw: 1,
    lost: 2,
    points: 22,
    goalsFor: 24,
    goalsAgainst: 12,
    goalDifference: 12,
  },
  {
    position: 4,
    teamId: 71,
    teamName: "Paris Saint-Germain",
    playedGames: 10,
    won: 6,
    draw: 2,
    lost: 2,
    points: 20,
    goalsFor: 22,
    goalsAgainst: 14,
    goalDifference: 8,
  },
  {
    position: 5,
    teamId: 68,
    teamName: "Juventus",
    playedGames: 10,
    won: 5,
    draw: 3,
    lost: 2,
    points: 18,
    goalsFor: 18,
    goalsAgainst: 12,
    goalDifference: 6,
  },
];

export const mockScorers = [
  {
    playerName: "Cristiano Ronaldo",
    teamName: "Al Nassr",
    goals: 32,
    assists: 5,
  },
  {
    playerName: "Lionel Messi",
    teamName: "Inter Miami",
    goals: 28,
    assists: 8,
  },
  {
    playerName: "Erling Haaland",
    teamName: "Manchester City",
    goals: 36,
    assists: 6,
  },
  {
    playerName: "Harry Kane",
    teamName: "Bayern Munich",
    goals: 30,
    assists: 7,
  },
  {
    playerName: "Kylian Mbappé",
    teamName: "Paris Saint-Germain",
    goals: 27,
    assists: 9,
  },
];
